### ISSUE TITLE
Remove Readme.txt

### ISSUE THREAD

**Issue by idget** [idget/Minecraft-Computercraft-Cave-Explorer#4]
The file is a duplicate of the .md file

**Comment by saksham15082** [comment]
please let me do it .I am not being able to get my first pull request.

**Comment by saksham-s** [comment]
I have sent a pull request

**Comment by saksham-s** [comment]
@idget please merge my request.

**Comment by saksham-s** [comment]
@idget  my pull request has been merged right?

**Comment by roastchicken** [comment]
Why do you make pull requests for simple things like this instead of just removing it yourself? It's literally just `git rm file.txt`, `git commit -m "Remove file.txt"`, and `git push`.

**Comment by idget** [comment]
@roastchicken I am trying to help some of the hacktoberfest people.
